### ISSUE TITLE
Add font-size control to Keppler

### ISSUE THREAD

**Issue by Tom-Bonnike** [brunosimon/keppler#11]

**Comment by brunosimon** [comment]
Would it be only for the code or for every fonts (sidebar, header, etc.) ?

**Comment by Tom-Bonnike** [comment]
Good question.
What we need is a way to zoom the text in the editor without scaling everything else.
Wouldn’t a normal browser zoom suffice for the other elements?
I don’t know.

**Comment by brunosimon** [comment]
Browser zoom works fine and I don't want complicate Keppler UX.
I'll close this one.
