### ISSUE TITLE
Delete “always last version” toggle

### ISSUE THREAD

**Issue by Tom-Bonnike** [brunosimon/keppler#18]
I believe we said it should work as such:
- If the user is on the last version of a file, it should automatically go to the latest version on every change
- If the user is on an older version of the file (if he manually clicked to see it), the latest version shouldn’t be automatically shown.

Maybe we need to design a way so that people know they’re not on the last version though? Related to #14

**Comment by brunosimon** [comment]
Yes it should work like that.
I term of UX, we probably need an easy way to go to the last version. Maybe this one can always be visible even if we scroll through the different version.
But yes, the last version should be visually more obvious.
