### ISSUE TITLE
Turning off version history blocks updates of file contents

### ISSUE THREAD

**Issue by mapio** [brunosimon/keppler#32]
Tested on  "Google Chrome" Version 63.0.3239.108 (Official Build) (64-bit) on OS X (macOS Sierra 10.12.6). 

When you toggle "version history", the file contents are not updated when changes are made on files (or when another file is selected in the web app).

**Comment by brunosimon** [comment]
Hello and thank you for the report.
It's fixed now and it'll be pushed shortly.

**Comment by mapio** [comment]
Thank you!
