### ISSUE TITLE
Disable spellcheck on code blocks

### ISSUE THREAD

**Issue by darahak** [brunosimon/keppler#33]
Most browsers have built-in spellcheckers now: using Chrome, every time I click on a line, it becomes underlined with a red squiggly line.

I know it can be disabled, but students might not be aware of this and think there is something wrong with the code.

For reference: [`spellcheck` attribute on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck)

Anyway, the project looks awesome. Looking forward to seeing it grow. Thank you! :bowing_man:

**Comment by brunosimon** [comment]
Hello,

Chrome spell checks never shows up for me inside Keppler.
I added the `spellcheck="false"` attribute and I published to NPM.
If you can check if it's working fine now, that would be awesome :)

Thank you for the help

**Comment by darahak** [comment]
Just tested the latest release, problem solved.
Thanks!
