### ISSUE TITLE
Download whole project fails after first download

### ISSUE THREAD

**Issue by edongashi** [brunosimon/keppler#36]
We have been experiencing the following issue on Keppler 1.4.0 hosted on Win7 x64:

The first project downloads successfully (`project > zip - create)`, while other downloads (`project > zip - from cache`) return a corrupt 0 byte file.

I suspect something is wrong with caching here. The presentations are hosted in LAN therefore performance is not an issue. If you can't resolve the problem, having an option to disable caching would be a good workaround for me.

Thank you!

**Comment by brunosimon** [comment]
Hi @edongashi 

Thanks for the report. It's now fix. Plz update to the latest version of Keppler.
