### ISSUE TITLE
php files not closed by ?> are not displayed in Keppler

### ISSUE THREAD

**Issue by blawniczak** [brunosimon/keppler#45]
It's all in the title. The php files that do not have the closing php tag ( ?> ) are not displayed in Keppler. This is a normal use of php in frameworks like Laravel for example.

**Comment by blawniczak** [comment]
Thank you :)

**Comment by cba85** [comment]
Just for information, I use Keppler with my students a lot for PHP and Laravel projects and I'd never had this issue (using last version of Keppler and node 12.19.0 and npm 6.14.8).

![192 168 1 20_1571_](https://user-images.githubusercontent.com/720547/103630185-9e2ab680-4f41-11eb-9f3f-97405461aec9.png)
