### ISSUE TITLE
Projects 404 page

### ISSUE THREAD

**Issue by Tom-Bonnike** [brunosimon/keppler#5]

**Comment by brunosimon** [comment]
For the projects yes.
Does the website need one ?

**Comment by Tom-Bonnike** [comment]
Yes, for the projects. I guess we’ll add more details for what we need exactly for the website later in the other issue. :)

**Comment by Tom-Bonnike** [comment]
Might not be needed if we cut down Keppler to one page
Needs discussion about multiple hosts in the same network/which project to prioritize
