### ISSUE TITLE
Allow multiple files to be opened “at the same time”

### ISSUE THREAD

**Issue by Tom-Bonnike** [brunosimon/keppler#9]
- [x] It should be used as a way to “pin/favorite” files, so that they do not always have to search for the files they care about in case the project is big.
- [x] There should be a way to quickly switch between the “pinned” files (keyboard shortcut, easy to access)
- [x] There should be a way to quickly see the file name, and maybe the language used (language icon?)
- [x] There should be a way to quickly see basic informations about the file: if new modifications have been added, etc…

The most obvious solution would be a tab system, but that’s up to us.

**Comment by brunosimon** [comment]
With tabs or with something else.
I can see Sublime users having "current files" in top of the sidebar. I don't use this feature but some people do.
But tabs are fine to me.
